### ISSUE TITLE
The CLI doesn't work on Windows

### ISSUE THREAD

**Issue by sgpopov** [MentorMate/node-pipeline-template#15]
I've encountered a few issues while testing the CLI on a Windows machine:

1. `pwd` is not recognized as an internal or external command

![windows-cmd-error](https://user-images.githubusercontent.com/1070710/193572919-14d4ecbd-577b-467b-8220-1feed7a2fab8.PNG)

2. While testing with Git Bash, there was another error thrown:

![windows-error](https://user-images.githubusercontent.com/1070710/193572938-4b9647a7-a1ac-478c-923f-a1271c9f9191.PNG)

## Context

* Operating Systems:  Windows 10
* Node version: 16.17.1 (npm v8.15.0)
* Node CLI version: 1.0.0-beta.5
* Terminals: PowerShell, Command Prompt, Git Bash (mingw64)

**Comment by Yavorss** [comment]
https://github.com/MentorMate/node-pipeline-template/pull/24
